-- MySQL Script generated by MySQL Workbench
-- Fri Aug 18 19:07:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pos` ;

-- -----------------------------------------------------
-- Schema pos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pos` ;

-- -----------------------------------------------------
-- Table `pos`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`categorias` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pos`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pos`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`ventas` (
  `venta_id` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`venta_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pos`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`productos` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`producto_id`),
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `pos`.`categorias` (`categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `categoria_id` ON `pos`.`productos` (`categoria_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pos`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`mesas` (
  `mesa_id` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`mesa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pos`.`detalles_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`detalles_venta` (
  `detalle_id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `precio_venta` DECIMAL(10,2) NOT NULL,
  `cliente_id` INT NOT NULL,
  `mesa_id` INT NOT NULL,
  PRIMARY KEY (`detalle_id`),
  CONSTRAINT `detalles_venta_ibfk_1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `pos`.`ventas` (`venta_id`),
  CONSTRAINT `detalles_venta_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `pos`.`productos` (`producto_id`),
  CONSTRAINT `fk_detalles_venta_clientes1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `pos`.`clientes` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_venta_mesas1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `pos`.`mesas` (`mesa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `pos`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `pos`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`role_id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `pos`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pos`.`user_roles` (
  `user_role_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_role_id`),
  CONSTRAINT `fk_user_roles_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `pos`.`users` (`user_id`),
  CONSTRAINT `fk_user_roles_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `pos`.`roles` (`role_id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- Add user_id column to the `ventas` table
ALTER TABLE `pos`.`ventas`
ADD COLUMN `user_id` INT NULL,
ADD CONSTRAINT `fk_ventas_users`
  FOREIGN KEY (`user_id`)
  REFERENCES `pos`.`users` (`user_id`);

CREATE INDEX `venta_id` ON `pos`.`detalles_venta` (`venta_id` ASC) VISIBLE;

CREATE INDEX `producto_id` ON `pos`.`detalles_venta` (`producto_id` ASC) VISIBLE;

CREATE INDEX `fk_detalles_venta_clientes1_idx` ON `pos`.`detalles_venta` (`cliente_id` ASC) VISIBLE;

CREATE INDEX `fk_detalles_venta_mesas1_idx` ON `pos`.`detalles_venta` (`mesa_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
